In [2]:
import numpy as np
import math

In [3]:
matrix_a = np.random.randint(3,size=(56,56,256))

In [4]:
shape = matrix_a.shape[-1]
matrix_a = matrix_a.reshape(-1,shape)

In [11]:
np.dot(matrix_a.T,matrix_a)

array([[5218, 3089, 3077, ..., 3123, 3183, 3040],
       [3089, 5219, 3039, ..., 3157, 3195, 3219],
       [3077, 3039, 5107, ..., 3128, 3192, 3103],
       ...,
       [3123, 3157, 3128, ..., 5269, 3185, 3171],
       [3183, 3195, 3192, ..., 3185, 5304, 3237],
       [3040, 3219, 3103, ..., 3171, 3237, 5223]])

In [12]:
np.dot(matrix_a,matrix_a.T)

array([[437, 278, 226, ..., 265, 267, 265],
       [278, 444, 241, ..., 274, 246, 275],
       [226, 241, 378, ..., 232, 242, 233],
       ...,
       [265, 274, 232, ..., 418, 255, 264],
       [267, 246, 242, ..., 255, 414, 257],
       [265, 275, 233, ..., 264, 257, 418]])

In [13]:
matrix_a = np.random.randint(3,size=(56,56,256))

In [14]:
np.dot(matrix_a.T,matrix_a)

array([[[[68, 74, 58, ..., 59, 75, 60],
         [54, 42, 61, ..., 49, 56, 60],
         [57, 72, 73, ..., 57, 60, 59],
         ...,
         [66, 71, 67, ..., 57, 38, 76],
         [58, 58, 72, ..., 77, 67, 73],
         [59, 71, 57, ..., 64, 61, 46]],

        [[50, 70, 59, ..., 62, 70, 47],
         [78, 53, 59, ..., 44, 64, 58],
         [52, 61, 74, ..., 67, 67, 59],
         ...,
         [64, 81, 52, ..., 54, 54, 72],
         [60, 67, 67, ..., 74, 66, 56],
         [72, 72, 48, ..., 64, 58, 50]],

        [[64, 71, 62, ..., 53, 75, 49],
         [68, 50, 49, ..., 54, 65, 53],
         [46, 58, 76, ..., 61, 57, 64],
         ...,
         [64, 72, 51, ..., 46, 58, 71],
         [57, 70, 69, ..., 71, 64, 55],
         [63, 73, 49, ..., 56, 66, 52]],

        ...,

        [[58, 69, 61, ..., 49, 80, 62],
         [59, 45, 52, ..., 52, 63, 51],
         [42, 68, 68, ..., 65, 57, 54],
         ...,
         [60, 60, 43, ..., 50, 42, 72],
         [55, 57, 58, ..., 67, 60, 57],
    